### ISSUE TITLE
use default prom node-exporter

### ISSUE THREAD

**Issue by davemasselink** [elevated-systems/compute-gardener-scheduler#23]
Perhaps don't need our own node-exporter to gather dynamic cpu freq info. the default prom node-exporter should be gathering this or could be made to.

confirm this to be the case (seeing data in prom, etc.) and then remove portions of our codebase 

=======

Standard node-exporter capabilities:
The standard Prometheus node-exporter does collect CPU frequency data out of the box! Looking at the [node-exporter documentation](https://github.com/prometheus/node_exporter), it exposes:

node_cpu_scaling_frequency_hertz - Current cpu thread scaling frequency in hertz
node_cpu_scaling_frequency_max_hertz - Maximum cpu thread scaling frequency in hertz
node_cpu_scaling_frequency_min_hertz - Minimum cpu thread scaling frequency in hertz

What you could do instead:

Use standard node-exporter image (e.g., prom/node-exporter:latest)
Create Prometheus recording rules to transform the data into your desired format:

```yaml
groups:
  - name: compute_gardener_cpu_metrics
    interval: 15s
    rules:
      # Convert Hz to GHz for easier consumption
      - record: compute_gardener:cpu_frequency_ghz
        expr: node_cpu_scaling_frequency_hertz / 1000000000
        
      # Calculate average frequency across all CPUs
      - record: compute_gardener:cpu_frequency_avg_ghz
        expr: avg(node_cpu_scaling_frequency_hertz) / 1000000000
```

For CPU model detection, you have two options:

Use node-exporter's node_dmi_info metric which includes system info
Use a simple init container or Job that runs once to label nodes:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: node-cpu-labeler
spec:
  template:
    spec:
      serviceAccountName: node-labeler
      containers:
      - name: labeler
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          # Get CPU model
          CPU_MODEL=$(cat /proc/cpuinfo | grep "model name" | head -1 | cut -d: -f2 | xargs)
          # Use kubectl to label the node
          kubectl label node $NODE_NAME "compute-gardener.io/cpu-model=$CPU_MODEL" --overwrite
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

Benefits of this approach:

No custom image to maintain - Use standard prom/node-exporter
Automatic updates - Benefit from node-exporter improvements
Broader compatibility - Many clusters already have node-exporter
Simpler deployment - Just a DaemonSet + recording rules

Modified deployment:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest  # Standard image!
        args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
        - --collector.netclass.ignored-devices=^(veth.*|[a-z0-9]+_[a-z0-9]+)$$
        - --collector.netdev.device-exclude=^(veth.*|[a-z0-9]+_[a-z0-9]+)$$
        ports:
        - containerPort: 9100
          name: metrics
        volumeMounts:
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
```

What about GPU metrics?
For GPU metrics, you'd still need DCGM exporter or `nvidia-gpu-exporter`, but those are also standard components you don't need to build.

Conclusion:
You can absolutely eliminate your custom node-exporter! The standard node-exporter already collects CPU frequency data. You'd just need:

Standard node-exporter DaemonSet
Some Prometheus recording rules to format the data
A simple job/script to label nodes with CPU models (or read from node_dmi_info)

This would significantly reduce your codebase and maintenance burden. The only "custom" part would be the recording rules and maybe a simple labeling script.
